#!/bin/bash

# Script para actualizar las credenciales de Supabase

echo "🔧 Actualizando credenciales de Supabase..."

cat > utils/supabase/info.tsx << 'EOF'
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ldqohbdvwpsxakjkrjqu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkcW9oYmR2d3BzeGFramtyanF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4ODgyNjMsImV4cCI6MjA5NjQ2NDI2M30.GdKOyJRXdIcyczu4vdAXuSroCEMIhDvOvoLhu9g60zQ"
EOF

echo "✅ Credenciales actualizadas!"
echo ""
echo "Ahora ejecuta en Supabase SQL Editor:"
echo "https://supabase.com/dashboard/project/ldqohbdvwpsxakjkrjqu/sql/new"
echo ""
echo "Copia el contenido de: ejecutar-en-supabase.sql"
