/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bvaiqkuhorlghbproljd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YWlxa3Vob3JsZ2hicHJvbGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1Mjc4MjcsImV4cCI6MjA5NzEwMzgyN30.zXjr4d-usmwmzji5ZfE-hDRf6CuaGn9K7XqmYKfoiq8"